# Generated by Django 5.2 on 2025-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
