# Generated by Django 5.1.2 on 2024-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='street',
        ),
    ]
