# Generated by Django 5.1.2 on 2024-11-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='shipping.county')),
            ],
            options={
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='shipping.town')),
            ],
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
