# Generated by Django 5.1.2 on 2024-11-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_location_order_address_and_more'),
        ('shipping', '0002_county_remove_shippingaddress_order_town_pickuppoint_and_more'),
        ('users', '0003_rename_address_line_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('delivery_type', models.CharField(choices=[('door_delivery', 'Door Delivery'), ('pickup_point', 'Pickup Point')], default='door_delivery', max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='users.address')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.pickuppoint')),
            ],
        ),
    ]
