# Generated by Django 5.1.2 on 2024-11-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0002_county_remove_shippingaddress_order_town_pickuppoint_and_more'),
        ('users', '0003_rename_address_line_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('door_delivery', 'Door Delivery'), ('pickup', 'Pickup Point')], default='door_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.pickuppoint'),
        ),
    ]
